### ISSUE TITLE
How to upload profile image?

### ISSUE THREAD

**Issue by zohaad** [tonarino/blog#4]
In `byline.tsx` on line 24 there's being referred to a `profiles/` folder, where do I create this?

**Comment by bschwind** [comment]
Hi @zohaad , sorry this wasn't clear! The `profiles/` directory will be within the `public/` directory.

I just added an empty directory in this template so you can see where it's located:

https://github.com/tonarino/blog/tree/e030629e6c0b5418d054c85a68396f625c2f21e5/public/profiles

**Comment by zohaad** [comment]
Awesome, thanks!
